apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: online-shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
      - name: online-shop
        image: swastik2929/online-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: online-shop-config
        
