apiVersion: v1
kind: Service
metadata:
  name: online-shop
  namespace: online-shopping
spec:
  selector:
    app: online-shop
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
